In [60]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import joblib
from sklearn import tree

music_data = pd.read_csv("music.csv")

In [22]:
music_data

    age  gender      genre
0    20       1     HipHop
1    23       1     HipHop
2    25       1     HipHop
3    26       1       Jazz
4    29       1       Jazz
5    30       1       Jazz
6    31       1  Classical
7    33       1  Classical
8    37       1  Classical
9    20       0      Dance
10   21       0      Dance
11   25       0      Dance
12   26       0   Acoustic
13   27       0   Acoustic
14   30       0   Acoustic
15   31       0  Classical
16   34       0  Classical
17   35       0  Classical

In [23]:
X = music_data.drop(columns=['genre'])

In [24]:
X

    age  gender
0    20       1
1    23       1
2    25       1
3    26       1
4    29       1
5    30       1
6    31       1
7    33       1
8    37       1
9    20       0
10   21       0
11   25       0
12   26       0
13   27       0
14   30       0
15   31       0
16   34       0
17   35       0

In [25]:
Y = music_data['genre']

In [26]:
Y

0        HipHop
1        HipHop
2        HipHop
3          Jazz
4          Jazz
5          Jazz
6     Classical
7     Classical
8     Classical
9         Dance
10        Dance
11        Dance
12     Acoustic
13     Acoustic
14     Acoustic
15    Classical
16    Classical
17    Classical
Name: genre, dtype: object

In [46]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y, test_size=0.2)

In [61]:
model = DecisionTreeClassifier()
model.fit(X_train,Y_train)

DecisionTreeClassifier()

In [63]:
tree.export_graphviz(model, out_file='music-recommender.dot',feature_names=['age','gender'],class_names=sorted(Y.unique()),label="all", rounded=True, filled=True )

In [55]:
# joblib.dump(model,'music-recommender.joblib')

['music-recommender.joblib']

In [56]:
# model = joblib.load('music-recommender.joblib')

In [57]:
predictions = model.predict(X_test)

In [58]:
accuracy_score(Y_test,predictions)

1.0

In [59]:
predictions

array(['Acoustic', 'Dance', 'Jazz', 'HipHop'], dtype=object)